name: CI

on:
  push:
    branches: [main, feature/*, hotfix/*]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    strategy:
      matrix:
        node-version: ['18', '20']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node version ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Log debug information
      run: |
        node --version
        npm --version

    - name: Install dependencies
      run: npm install

    - name: Run linters
      run: npm run lint

    - name: Run build
      run: npm run build
